//Tags from typescript DOM lib 5.2.2 (typescript/lib/lib.dom.d.ts)

import { ObSetter, mkElement } from "./dom";

type C = ObSetter[];

export const a = (...c: C) => mkElement("a", ...c); //HTMLAnchorElement
export const abbr = (...c: C) => mkElement("abbr", ...c); //HTMLElement
export const address = (...c: C) => mkElement("address", ...c); //HTMLElement
export const area = (...c: C) => mkElement("area", ...c); //HTMLAreaElement
export const article = (...c: C) => mkElement("article", ...c); //HTMLElement
export const aside = (...c: C) => mkElement("aside", ...c); //HTMLElement
export const audio = (...c: C) => mkElement("audio", ...c); //HTMLAudioElement
export const b = (...c: C) => mkElement("b", ...c); //HTMLElement
export const base = (...c: C) => mkElement("base", ...c); //HTMLBaseElement
export const bdi = (...c: C) => mkElement("bdi", ...c); //HTMLElement
export const bdo = (...c: C) => mkElement("bdo", ...c); //HTMLElement
export const blockquote = (...c: C) => mkElement("blockquote", ...c); //HTMLQuoteElement
export const body = (...c: C) => mkElement("body", ...c); //HTMLBodyElement
export const br = (...c: C) => mkElement("br", ...c); //HTMLBRElement
export const button = (...c: C) => mkElement("button", ...c); //HTMLButtonElement
export const canvas = (...c: C) => mkElement("canvas", ...c); //HTMLCanvasElement
export const caption = (...c: C) => mkElement("caption", ...c); //HTMLTableCaptionElement
export const cite = (...c: C) => mkElement("cite", ...c); //HTMLElement
export const code = (...c: C) => mkElement("code", ...c); //HTMLElement
export const col = (...c: C) => mkElement("col", ...c); //HTMLTableColElement
export const colgroup = (...c: C) => mkElement("colgroup", ...c); //HTMLTableColElement
export const data = (...c: C) => mkElement("data", ...c); //HTMLDataElement
export const datalist = (...c: C) => mkElement("datalist", ...c); //HTMLDataListElement
export const dd = (...c: C) => mkElement("dd", ...c); //HTMLElement
export const del = (...c: C) => mkElement("del", ...c); //HTMLModElement
export const details = (...c: C) => mkElement("details", ...c); //HTMLDetailsElement
export const dfn = (...c: C) => mkElement("dfn", ...c); //HTMLElement
export const dialog = (...c: C) => mkElement("dialog", ...c); //HTMLDialogElement
export const div = (...c: C) => mkElement("div", ...c); //HTMLDivElement
export const dl = (...c: C) => mkElement("dl", ...c); //HTMLDListElement
export const dt = (...c: C) => mkElement("dt", ...c); //HTMLElement
export const em = (...c: C) => mkElement("em", ...c); //HTMLElement
export const embed = (...c: C) => mkElement("embed", ...c); //HTMLEmbedElement
export const fieldset = (...c: C) => mkElement("fieldset", ...c); //HTMLFieldSetElement
export const figcaption = (...c: C) => mkElement("figcaption", ...c); //HTMLElement
export const figure = (...c: C) => mkElement("figure", ...c); //HTMLElement
export const footer = (...c: C) => mkElement("footer", ...c); //HTMLElement
export const form = (...c: C) => mkElement("form", ...c); //HTMLFormElement
export const h1 = (...c: C) => mkElement("h1", ...c); //HTMLHeadingElement
export const h2 = (...c: C) => mkElement("h2", ...c); //HTMLHeadingElement
export const h3 = (...c: C) => mkElement("h3", ...c); //HTMLHeadingElement
export const h4 = (...c: C) => mkElement("h4", ...c); //HTMLHeadingElement
export const h5 = (...c: C) => mkElement("h5", ...c); //HTMLHeadingElement
export const h6 = (...c: C) => mkElement("h6", ...c); //HTMLHeadingElement
export const head = (...c: C) => mkElement("head", ...c); //HTMLHeadElement
export const header = (...c: C) => mkElement("header", ...c); //HTMLElement
export const hgroup = (...c: C) => mkElement("hgroup", ...c); //HTMLElement
export const hr = (...c: C) => mkElement("hr", ...c); //HTMLHRElement
export const html = (...c: C) => mkElement("html", ...c); //HTMLHtmlElement
export const i = (...c: C) => mkElement("i", ...c); //HTMLElement
export const iframe = (...c: C) => mkElement("iframe", ...c); //HTMLIFrameElement
export const img = (...c: C) => mkElement("img", ...c); //HTMLImageElement
export const input = (...c: C) => mkElement("input", ...c); //HTMLInputElement
export const ins = (...c: C) => mkElement("ins", ...c); //HTMLModElement
export const kbd = (...c: C) => mkElement("kbd", ...c); //HTMLElement
export const label = (...c: C) => mkElement("label", ...c); //HTMLLabelElement
export const legend = (...c: C) => mkElement("legend", ...c); //HTMLLegendElement
export const li = (...c: C) => mkElement("li", ...c); //HTMLLIElement
export const link = (...c: C) => mkElement("link", ...c); //HTMLLinkElement
export const main = (...c: C) => mkElement("main", ...c); //HTMLElement
export const map = (...c: C) => mkElement("map", ...c); //HTMLMapElement
export const mark = (...c: C) => mkElement("mark", ...c); //HTMLElement
export const menu = (...c: C) => mkElement("menu", ...c); //HTMLMenuElement
export const meta = (...c: C) => mkElement("meta", ...c); //HTMLMetaElement
export const meter = (...c: C) => mkElement("meter", ...c); //HTMLMeterElement
export const nav = (...c: C) => mkElement("nav", ...c); //HTMLElement
export const noscript = (...c: C) => mkElement("noscript", ...c); //HTMLElement
export const object = (...c: C) => mkElement("object", ...c); //HTMLObjectElement
export const ol = (...c: C) => mkElement("ol", ...c); //HTMLOListElement
export const optgroup = (...c: C) => mkElement("optgroup", ...c); //HTMLOptGroupElement
export const option = (...c: C) => mkElement("option", ...c); //HTMLOptionElement
export const output = (...c: C) => mkElement("output", ...c); //HTMLOutputElement
export const p = (...c: C) => mkElement("p", ...c); //HTMLParagraphElement
export const picture = (...c: C) => mkElement("picture", ...c); //HTMLPictureElement
export const pre = (...c: C) => mkElement("pre", ...c); //HTMLPreElement
export const progress = (...c: C) => mkElement("progress", ...c); //HTMLProgressElement
export const q = (...c: C) => mkElement("q", ...c); //HTMLQuoteElement
export const rp = (...c: C) => mkElement("rp", ...c); //HTMLElement
export const rt = (...c: C) => mkElement("rt", ...c); //HTMLElement
export const ruby = (...c: C) => mkElement("ruby", ...c); //HTMLElement
export const s = (...c: C) => mkElement("s", ...c); //HTMLElement
export const samp = (...c: C) => mkElement("samp", ...c); //HTMLElement
export const script = (...c: C) => mkElement("script", ...c); //HTMLScriptElement
export const search = (...c: C) => mkElement("search", ...c); //HTMLElement
export const section = (...c: C) => mkElement("section", ...c); //HTMLElement
export const select = (...c: C) => mkElement("select", ...c); //HTMLSelectElement
export const slot = (...c: C) => mkElement("slot", ...c); //HTMLSlotElement
export const small = (...c: C) => mkElement("small", ...c); //HTMLElement
export const source = (...c: C) => mkElement("source", ...c); //HTMLSourceElement
export const span = (...c: C) => mkElement("span", ...c); //HTMLSpanElement
export const strong = (...c: C) => mkElement("strong", ...c); //HTMLElement
// added "Tag" suffix to avoid confusion with commonly used "style" attribute
export const styleTag = (...c: C) => mkElement("style", ...c); //HTMLStyleElement
export const sub = (...c: C) => mkElement("sub", ...c); //HTMLElement
export const summary = (...c: C) => mkElement("summary", ...c); //HTMLElement
export const sup = (...c: C) => mkElement("sup", ...c); //HTMLElement
export const table = (...c: C) => mkElement("table", ...c); //HTMLTableElement
export const tbody = (...c: C) => mkElement("tbody", ...c); //HTMLTableSectionElement
export const td = (...c: C) => mkElement("td", ...c); //HTMLTableCellElement
export const template = (...c: C) => mkElement("template", ...c); //HTMLTemplateElement
export const textarea = (...c: C) => mkElement("textarea", ...c); //HTMLTextAreaElement
export const tfoot = (...c: C) => mkElement("tfoot", ...c); //HTMLTableSectionElement
export const th = (...c: C) => mkElement("th", ...c); //HTMLTableCellElement
export const thead = (...c: C) => mkElement("thead", ...c); //HTMLTableSectionElement
export const time = (...c: C) => mkElement("time", ...c); //HTMLTimeElement
export const title = (...c: C) => mkElement("title", ...c); //HTMLTitleElement
export const tr = (...c: C) => mkElement("tr", ...c); //HTMLTableRowElement
export const track = (...c: C) => mkElement("track", ...c); //HTMLTrackElement
export const u = (...c: C) => mkElement("u", ...c); //HTMLElement
export const ul = (...c: C) => mkElement("ul", ...c); //HTMLUListElement
// added "Tag" suffix to avoid conflict with TS keyword
export const varTag = (...c: C) => mkElement("var", ...c); //HTMLElement
export const video = (...c: C) => mkElement("video", ...c); //HTMLVideoElement
export const wbr = (...c: C) => mkElement("wbr", ...c); //HTMLElement
